astro_root: /root/wyj/map-anything-sdss/astro_sdss_v2_20gb_curated
train_manifest: ${dataset.astro_root}/manifest/train_ready_train.jsonl
val_manifest: ${dataset.astro_root}/manifest/train_ready_val.jsonl
stats_manifest: ${dataset.train_manifest}
stats_cache_path: ${dataset.astro_root}/manifest/astro_train_norm_stats_v2.json

num_views: 2
num_workers: 8
resolution_train: [224, 224]
resolution_val: [224, 224]
principal_point_centered: false

train:
  variable_num_views: false
val:
  variable_num_views: false
test:
  variable_num_views: false

train_dataset:
  "4_000 @ AstroSDSSPairDatasetV2(
  manifest_path='${dataset.train_manifest}',
  split='train',
  use_metadata=True,
  mask_ratio_image=(0.0, 0.0),
  mask_ratio_spec=(0.15, 0.35),
  seed=42,
  eval_fixed_mask=False,
  image_size=224,
  image_patch_size=7,
  spec_length=2048,
  spec_span_min=8,
  spec_span_max=48,
  modality_probs_stage_b=(0.25, 0.15, 0.60),
  modality_probs_stage_c=(0.30, 0.15, 0.55),
  eval_modality_probs=(0.25, 0.15, 0.60),
  stage_a_epochs=20,
  stage_b_epochs=80,
  stage_c_epochs=20,
  mask_schedule_epochs=120,
  stats_manifest_path='${dataset.stats_manifest}',
  stats_cache_path='${dataset.stats_cache_path}',
  num_views=${dataset.num_views},
  variable_num_views=${dataset.train.variable_num_views},
  resolution=(224, 224),
  data_norm_type='identity',
  enable_band_masking=True,
  band_mask_count_range=(0, 1),
  enable_sparse_patch_dropout=True,
  sparse_patch_dropout_ratio=(0.02, 0.08),
  enable_spectrum_input_masking=True,
  use_raw_spectrum_aux_targets=True,
  raw_spectrum_aux_keys=('flux_obs', 'flux_rest'))"

test_dataset:
  "512 @ AstroSDSSPairDatasetV2(
  manifest_path='${dataset.val_manifest}',
  split='val',
  use_metadata=True,
  mask_ratio_image=(0.0, 0.0),
  mask_ratio_spec=(0.15, 0.35),
  seed=42,
  eval_fixed_mask=True,
  image_size=224,
  image_patch_size=7,
  spec_length=2048,
  spec_span_min=8,
  spec_span_max=48,
  modality_probs_stage_b=(0.25, 0.15, 0.60),
  modality_probs_stage_c=(0.30, 0.15, 0.55),
  eval_modality_probs=(0.25, 0.15, 0.60),
  stage_a_epochs=20,
  stage_b_epochs=80,
  stage_c_epochs=20,
  mask_schedule_epochs=120,
  stats_manifest_path='${dataset.stats_manifest}',
  stats_cache_path='${dataset.stats_cache_path}',
  num_views=${dataset.num_views},
  variable_num_views=${dataset.val.variable_num_views},
  resolution=(224, 224),
  data_norm_type='identity',
  enable_band_masking=True,
  band_mask_count_range=(0, 1),
  enable_sparse_patch_dropout=True,
  sparse_patch_dropout_ratio=(0.02, 0.08),
  enable_spectrum_input_masking=True,
  use_raw_spectrum_aux_targets=True,
  raw_spectrum_aux_keys=('flux_obs', 'flux_rest'))"
